package org.apache.torque.test;

import org.apache.torque.test.base.BaseProtectedColumnsRecordMapper;

/**
 * Maps ResultSet rows into ProtectedColumns objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class ProtectedColumnsRecordMapper extends BaseProtectedColumnsRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839169L;



}
