package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages Abstract objects.
 *
 * table with abstract OM class
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to AbstractBean
 */
 
public class AbstractManager
    extends org.apache.torque.test.manager.base.BaseAbstractManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841851L;


    /**
     * Creates a new <code>AbstractManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public AbstractManager()
        throws TorqueException
    {
        super();
    }

}
