package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages AutoincrementNative objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to AutoincrementNativeBean
 */
 
public class AutoincrementNativeManager
    extends org.apache.torque.test.manager.base.BaseAutoincrementNativeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841834L;


    /**
     * Creates a new <code>AutoincrementNativeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public AutoincrementNativeManager()
        throws TorqueException
    {
        super();
    }

}
