package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages AutoincrementNone objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to AutoincrementNoneBean
 */
 
public class AutoincrementNoneManager
    extends org.apache.torque.test.manager.base.BaseAutoincrementNoneManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841836L;


    /**
     * Creates a new <code>AutoincrementNoneManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public AutoincrementNoneManager()
        throws TorqueException
    {
        super();
    }

}
