package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages BaseTable objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to BaseTableBean
 */
 
public class BaseTableManager
    extends org.apache.torque.test.manager.base.BaseBaseTableManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841832L;


    /**
     * Creates a new <code>BaseTableManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BaseTableManager()
        throws TorqueException
    {
        super();
    }

}
