package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages BigintType objects.
 *
 * Table to test BIGINT type
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to BigintTypeBean
 */
 
public class BigintTypeManager
    extends org.apache.torque.test.manager.base.BaseBigintTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841901L;


    /**
     * Creates a new <code>BigintTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BigintTypeManager()
        throws TorqueException
    {
        super();
    }

}
