package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages BinaryType objects.
 *
 * Table to test BINARY type
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to BinaryTypeBean
 */
 
public class BinaryTypeManager
    extends org.apache.torque.test.manager.base.BaseBinaryTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841885L;


    /**
     * Creates a new <code>BinaryTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BinaryTypeManager()
        throws TorqueException
    {
        super();
    }

}
