package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages BintBcharType objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to BintBcharTypeBean
 */
 
public class BintBcharTypeManager
    extends org.apache.torque.test.manager.base.BaseBintBcharTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841893L;


    /**
     * Creates a new <code>BintBcharTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BintBcharTypeManager()
        throws TorqueException
    {
        super();
    }

}
