package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages BitCompositePk objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to BitCompositePkBean
 */
 
public class BitCompositePkManager
    extends org.apache.torque.test.manager.base.BaseBitCompositePkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841796L;


    /**
     * Creates a new <code>BitCompositePkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BitCompositePkManager()
        throws TorqueException
    {
        super();
    }

}
