package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages BitType objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to BitTypeBean
 */
 
public class BitTypeManager
    extends org.apache.torque.test.manager.base.BaseBitTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841879L;


    /**
     * Creates a new <code>BitTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BitTypeManager()
        throws TorqueException
    {
        super();
    }

}
