package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages BlobType objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to BlobTypeBean
 */
 
public class BlobTypeManager
    extends org.apache.torque.test.manager.base.BaseBlobTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841881L;


    /**
     * Creates a new <code>BlobTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BlobTypeManager()
        throws TorqueException
    {
        super();
    }

}
