package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages Book objects.
 *
 * Book table
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to BookBean
 */
 
public class BookManager
    extends org.apache.torque.test.manager.base.BaseBookManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841676L;


    /**
     * Creates a new <code>BookManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BookManager()
        throws TorqueException
    {
        super();
    }

}
