package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages CircularReferenceB objects.
 *
 * Table to test circular references
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to CircularReferenceBBean
 */
 
public class CircularReferenceBManager
    extends org.apache.torque.test.manager.base.BaseCircularReferenceBManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841769L;


    /**
     * Creates a new <code>CircularReferenceBManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public CircularReferenceBManager()
        throws TorqueException
    {
        super();
    }

}
