package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages CircularReferenceA objects.
 *
 * Table to test circular references
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to CircularReferenceABean
 */
 
public class CircularReferenceAManager
    extends org.apache.torque.test.manager.base.BaseCircularReferenceAManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841767L;


    /**
     * Creates a new <code>CircularReferenceAManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public CircularReferenceAManager()
        throws TorqueException
    {
        super();
    }

}
