package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages ClobType objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to ClobTypeBean
 */
 
public class ClobTypeManager
    extends org.apache.torque.test.manager.base.BaseClobTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841883L;


    /**
     * Creates a new <code>ClobTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public ClobTypeManager()
        throws TorqueException
    {
        super();
    }

}
