package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages CompNonpkFk objects.
 *
 * table with a composite foreign key consisting of an integer           and a varchar column, not pointing to the primary key            of the referenced table
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to CompNonpkFkBean
 */
 
public class CompNonpkFkManager
    extends org.apache.torque.test.manager.base.BaseCompNonpkFkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841764L;


    /**
     * Creates a new <code>CompNonpkFkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public CompNonpkFkManager()
        throws TorqueException
    {
        super();
    }

}
