package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages CompIntegerVarcharPk objects.
 *
 * table with a composite primary key consisting of an integer           and a varchar column
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to CompIntegerVarcharPkBean
 */
 
public class CompIntegerVarcharPkManager
    extends org.apache.torque.test.manager.base.BaseCompIntegerVarcharPkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841759L;


    /**
     * Creates a new <code>CompIntegerVarcharPkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public CompIntegerVarcharPkManager()
        throws TorqueException
    {
        super();
    }

}
