package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages CompPkOtherFk objects.
 *
 * table with a composite primary key which does not contain            the foreign key column which references the non-composite            primary key of another table
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to CompPkOtherFkBean
 */
 
public class CompPkOtherFkManager
    extends org.apache.torque.test.manager.base.BaseCompPkOtherFkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841753L;


    /**
     * Creates a new <code>CompPkOtherFkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public CompPkOtherFkManager()
        throws TorqueException
    {
        super();
    }

}
