package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages CompIntegerVarcharFk objects.
 *
 * table with a composite foreign key consisting of an integer           and a varchar column
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to CompIntegerVarcharFkBean
 */
 
public class CompIntegerVarcharFkManager
    extends org.apache.torque.test.manager.base.BaseCompIntegerVarcharFkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841762L;


    /**
     * Creates a new <code>CompIntegerVarcharFkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public CompIntegerVarcharFkManager()
        throws TorqueException
    {
        super();
    }

}
