package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages CurrentTimeTable objects.
 *
 * Table to test the CURRENT_TIME function
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to CurrentTimeTableBean
 */
 
public class CurrentTimeTableManager
    extends org.apache.torque.test.manager.base.BaseCurrentTimeTableManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841702L;


    /**
     * Creates a new <code>CurrentTimeTableManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public CurrentTimeTableManager()
        throws TorqueException
    {
        super();
    }

}
