package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages CurrentTimestampTable objects.
 *
 * Table to test the CURRENT_TIMESTAMP function
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to CurrentTimestampTableBean
 */
 
public class CurrentTimestampTableManager
    extends org.apache.torque.test.manager.base.BaseCurrentTimestampTableManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841704L;


    /**
     * Creates a new <code>CurrentTimestampTableManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public CurrentTimestampTableManager()
        throws TorqueException
    {
        super();
    }

}
