package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages CurrentDateTable objects.
 *
 * Table which has a column which uses CURRENT_DATE from the database as default
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to CurrentDateTableBean
 */
 
public class CurrentDateTableManager
    extends org.apache.torque.test.manager.base.BaseCurrentDateTableManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841699L;


    /**
     * Creates a new <code>CurrentDateTableManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public CurrentDateTableManager()
        throws TorqueException
    {
        super();
    }

}
