package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages DatabaseDefaultValues objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to DatabaseDefaultValuesBean
 */
 
public class DatabaseDefaultValuesManager
    extends org.apache.torque.test.manager.base.BaseDatabaseDefaultValuesManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841695L;


    /**
     * Creates a new <code>DatabaseDefaultValuesManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public DatabaseDefaultValuesManager()
        throws TorqueException
    {
        super();
    }

}
