package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages DateTimeTimestampType objects.
 *
 * Table to test Date formats
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to DateTimeTimestampTypeBean
 */
 
public class DateTimeTimestampTypeManager
    extends org.apache.torque.test.manager.base.BaseDateTimeTimestampTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841896L;


    /**
     * Creates a new <code>DateTimeTimestampTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public DateTimeTimestampTypeManager()
        throws TorqueException
    {
        super();
    }

}
