package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages DatePk objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to DatePkBean
 */
 
public class DatePkManager
    extends org.apache.torque.test.manager.base.BaseDatePkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841789L;


    /**
     * Creates a new <code>DatePkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public DatePkManager()
        throws TorqueException
    {
        super();
    }

}
