package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages EnumTable objects.
 *
 * this table is used for testing enum values in columns
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to EnumTableBean
 */
 
public class EnumTableManager
    extends org.apache.torque.test.manager.base.BaseEnumTableManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841864L;


    /**
     * Creates a new <code>EnumTableManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public EnumTableManager()
        throws TorqueException
    {
        super();
    }

}
