package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages Extext objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to ExtextBean
 */
 
public class ExtextManager
    extends org.apache.torque.test.manager.base.BaseExtextManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841821L;


    /**
     * Creates a new <code>ExtextManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public ExtextManager()
        throws TorqueException
    {
        super();
    }

}
