package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages Ext objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to ExtBean
 */
 
public class ExtManager
    extends org.apache.torque.test.manager.base.BaseExtManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841824L;


    /**
     * Creates a new <code>ExtManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public ExtManager()
        throws TorqueException
    {
        super();
    }

}
