package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages IncludedFromIncluded objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to IncludedFromIncludedBean
 */
 
public class IncludedFromIncludedManager
    extends org.apache.torque.test.manager.base.BaseIncludedFromIncludedManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841868L;


    /**
     * Creates a new <code>IncludedFromIncludedManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public IncludedFromIncludedManager()
        throws TorqueException
    {
        super();
    }

}
