package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages Included objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to IncludedBean
 */
 
public class IncludedManager
    extends org.apache.torque.test.manager.base.BaseIncludedManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841866L;


    /**
     * Creates a new <code>IncludedManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public IncludedManager()
        throws TorqueException
    {
        super();
    }

}
