package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages InheritanceTest objects.
 *
 * Table to test inheritance with mapped keys
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to InheritanceTestBean
 */
 
public class InheritanceTestManager
    extends org.apache.torque.test.manager.base.BaseInheritanceTestManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841842L;


    /**
     * Creates a new <code>InheritanceTestManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public InheritanceTestManager()
        throws TorqueException
    {
        super();
    }

}
