package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages InheritanceClassnameTest objects.
 *
 * Table to test inheritance with classnames stored in the inheritance column
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to InheritanceClassnameTestBean
 */
 
public class InheritanceClassnameTestManager
    extends org.apache.torque.test.manager.base.BaseInheritanceClassnameTestManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841844L;


    /**
     * Creates a new <code>InheritanceClassnameTestManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public InheritanceClassnameTestManager()
        throws TorqueException
    {
        super();
    }

}
