package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages IntegerType objects.
 *
 * Table to test INTEGER type
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to IntegerTypeBean
 */
 
public class IntegerTypeManager
    extends org.apache.torque.test.manager.base.BaseIntegerTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841898L;


    /**
     * Creates a new <code>IntegerTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public IntegerTypeManager()
        throws TorqueException
    {
        super();
    }

}
