package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages JavaDefaultValues objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to JavaDefaultValuesBean
 */
 
public class JavaDefaultValuesManager
    extends org.apache.torque.test.manager.base.BaseJavaDefaultValuesManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841697L;


    /**
     * Creates a new <code>JavaDefaultValuesManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public JavaDefaultValuesManager()
        throws TorqueException
    {
        super();
    }

}
