package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages LocalIfcTable objects.
 *
 * this table implements a local interface
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to LocalIfcTableBean
 */
 
public class LocalTestInterfaceManager
    extends org.apache.torque.test.manager.base.BaseLocalTestInterfaceManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841856L;


    /**
     * Creates a new <code>LocalTestInterfaceManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public LocalTestInterfaceManager()
        throws TorqueException
    {
        super();
    }

}
