package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages LongvarbinaryType objects.
 *
 * Table to test LONGVARBINARY type
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to LongvarbinaryTypeBean
 */
 
public class LongvarbinaryTypeManager
    extends org.apache.torque.test.manager.base.BaseLongvarbinaryTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841890L;


    /**
     * Creates a new <code>LongvarbinaryTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public LongvarbinaryTypeManager()
        throws TorqueException
    {
        super();
    }

}
