package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages MultiRefSameTable objects.
 *
 * Table to test multiple references to a same table
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to MultiRefSameTableBean
 */
 
public class MultiRefSameTableManager
    extends org.apache.torque.test.manager.base.BaseMultiRefSameTableManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841748L;


    /**
     * Creates a new <code>MultiRefSameTableManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public MultiRefSameTableManager()
        throws TorqueException
    {
        super();
    }

}
