package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages MultipleIndex objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to MultipleIndexBean
 */
 
public class MultipleIndexManager
    extends org.apache.torque.test.manager.base.BaseMultipleIndexManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841778L;


    /**
     * Creates a new <code>MultipleIndexManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public MultipleIndexManager()
        throws TorqueException
    {
        super();
    }

}
