package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages MultiPk objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to MultiPkBean
 */
 
public class MultiPkManager
    extends org.apache.torque.test.manager.base.BaseMultiPkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841798L;


    /**
     * Creates a new <code>MultiPkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public MultiPkManager()
        throws TorqueException
    {
        super();
    }

}
