package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages MultiRef objects.
 *
 * Table to test multiple references to different tables
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to MultiRefBean
 */
 
public class MultiRefManager
    extends org.apache.torque.test.manager.base.BaseMultiRefManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841750L;


    /**
     * Creates a new <code>MultiRefManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public MultiRefManager()
        throws TorqueException
    {
        super();
    }

}
