package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages MultipleUnique objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to MultipleUniqueBean
 */
 
public class MultipleUniqueManager
    extends org.apache.torque.test.manager.base.BaseMultipleUniqueManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841785L;


    /**
     * Creates a new <code>MultipleUniqueManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public MultipleUniqueManager()
        throws TorqueException
    {
        super();
    }

}
