package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages NonPkOIntegerFk objects.
 *
 * table with a nullable integer object foreign key           which references a non-primary-key column in the foreign table
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to NonPkOIntegerFkBean
 */
 
public class NonPkOIntegerFkManager
    extends org.apache.torque.test.manager.base.BaseNonPkOIntegerFkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841742L;


    /**
     * Creates a new <code>NonPkOIntegerFkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public NonPkOIntegerFkManager()
        throws TorqueException
    {
        super();
    }

}
