package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages NonPkPIntegerFk objects.
 *
 * table with a non-nullable integer primitive foreign key           which references a non-primary-key column in the foreign table
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to NonPkPIntegerFkBean
 */
 
public class NonPkPIntegerFkManager
    extends org.apache.torque.test.manager.base.BaseNonPkPIntegerFkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841724L;


    /**
     * Creates a new <code>NonPkPIntegerFkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public NonPkPIntegerFkManager()
        throws TorqueException
    {
        super();
    }

}
