package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages NotUsedBeforeMapInit objects.
 *
 * Table used for database map initialisation checks
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to NotUsedBeforeMapInitBean
 */
 
public class NotUsedBeforeMapInitManager
    extends org.apache.torque.test.manager.base.BaseNotUsedBeforeMapInitManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841683L;


    /**
     * Creates a new <code>NotUsedBeforeMapInitManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public NotUsedBeforeMapInitManager()
        throws TorqueException
    {
        super();
    }

}
