package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages NullablePIntegerFk objects.
 *
 * table with a nullable integer primitive foreign key           which references a primary key column in the foreign table
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to NullablePIntegerFkBean
 */
 
public class NullablePIntegerFkManager
    extends org.apache.torque.test.manager.base.BaseNullablePIntegerFkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841716L;


    /**
     * Creates a new <code>NullablePIntegerFkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public NullablePIntegerFkManager()
        throws TorqueException
    {
        super();
    }

}
