package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages OIntegerFkToPPk objects.
 *
 * table with a nullable integer object foreign key           which references a primitive primary key column in the foreign table
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to OIntegerFkToPPkBean
 */
 
public class OIntegerFkToPPkManager
    extends org.apache.torque.test.manager.base.BaseOIntegerFkToPPkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841728L;


    /**
     * Creates a new <code>OIntegerFkToPPkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public OIntegerFkToPPkManager()
        throws TorqueException
    {
        super();
    }

}
