package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages OIntegerFkWithDefault objects.
 *
 * table with a non-nullable integer object foreign key           which references a primary key column in the foreign table           and has a default value
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to OIntegerFkWithDefaultBean
 */
 
public class OIntegerFkWithDefaultManager
    extends org.apache.torque.test.manager.base.BaseOIntegerFkWithDefaultManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841739L;


    /**
     * Creates a new <code>OIntegerFkWithDefaultManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public OIntegerFkWithDefaultManager()
        throws TorqueException
    {
        super();
    }

}
