package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages OIntegerPk objects.
 *
 * table with a object integer pk
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to OIntegerPkBean
 */
 
public class OIntegerPkManager
    extends org.apache.torque.test.manager.base.BaseOIntegerPkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841731L;


    /**
     * Creates a new <code>OIntegerPkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public OIntegerPkManager()
        throws TorqueException
    {
        super();
    }

}
