package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages OptimisticLockingSimple objects.
 *
 * this table implements optimistic Locking with the simple select mode
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to OptimisticLockingSimpleBean
 */
 
public class OptimisticLockingSimpleManager
    extends org.apache.torque.test.manager.base.BaseOptimisticLockingSimpleManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841862L;


    /**
     * Creates a new <code>OptimisticLockingSimpleManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public OptimisticLockingSimpleManager()
        throws TorqueException
    {
        super();
    }

}
