package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages PIntegerFkToOPk objects.
 *
 * table with a nullable primitive int foreign key           which references a primitive primary key column in the foreign table
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to PIntegerFkToOPkBean
 */
 
public class PIntegerFkToOPkManager
    extends org.apache.torque.test.manager.base.BasePIntegerFkToOPkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841745L;


    /**
     * Creates a new <code>PIntegerFkToOPkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public PIntegerFkToOPkManager()
        throws TorqueException
    {
        super();
    }

}
