package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages PIntegerPk objects.
 *
 * table with a primitive int pk
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to PIntegerPkBean
 */
 
public class PIntegerPkManager
    extends org.apache.torque.test.manager.base.BasePIntegerPkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841713L;


    /**
     * Creates a new <code>PIntegerPkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public PIntegerPkManager()
        throws TorqueException
    {
        super();
    }

}
