package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages PIntegerFkWithDefault objects.
 *
 * table with a primitive integer foreign key           which references a primary key column in the foreign table           and has a default value
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to PIntegerFkWithDefaultBean
 */
 
public class PIntegerFkWithDefaultManager
    extends org.apache.torque.test.manager.base.BasePIntegerFkWithDefaultManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841721L;


    /**
     * Creates a new <code>PIntegerFkWithDefaultManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public PIntegerFkWithDefaultManager()
        throws TorqueException
    {
        super();
    }

}
