package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages ProtectedColumns objects.
 *
 * Table with protected getter methods for columns.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to ProtectedColumnsBean
 */
 
public class ProtectedColumnsManager
    extends org.apache.torque.test.manager.base.BaseProtectedColumnsManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841689L;


    /**
     * Creates a new <code>ProtectedColumnsManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public ProtectedColumnsManager()
        throws TorqueException
    {
        super();
    }

}
