package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages QualifiedName objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to QualifiedNameBean
 */
 
public class QualifiedNameManager
    extends org.apache.torque.test.manager.base.BaseQualifiedNameManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841802L;


    /**
     * Creates a new <code>QualifiedNameManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public QualifiedNameManager()
        throws TorqueException
    {
        super();
    }

}
