package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages ReferenceToIncluded objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to ReferenceToIncludedBean
 */
 
public class ReferenceToIncludedManager
    extends org.apache.torque.test.manager.base.BaseReferenceToIncludedManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841826L;


    /**
     * Creates a new <code>ReferenceToIncludedManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public ReferenceToIncludedManager()
        throws TorqueException
    {
        super();
    }

}
