package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages ReferenceToExtSchema objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to ReferenceToExtSchemaBean
 */
 
public class ReferenceToExtSchemaManager
    extends org.apache.torque.test.manager.base.BaseReferenceToExtSchemaManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841828L;


    /**
     * Creates a new <code>ReferenceToExtSchemaManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public ReferenceToExtSchemaManager()
        throws TorqueException
    {
        super();
    }

}
