package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages SecondMapInit objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to SecondMapInitBean
 */
 
public class SecondMapInitManager
    extends org.apache.torque.test.manager.base.BaseSecondMapInitManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841685L;


    /**
     * Creates a new <code>SecondMapInitManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public SecondMapInitManager()
        throws TorqueException
    {
        super();
    }

}
