package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages SingleNamedIndex objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to SingleNamedIndexBean
 */
 
public class SingleNamedIndexManager
    extends org.apache.torque.test.manager.base.BaseSingleNamedIndexManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841773L;


    /**
     * Creates a new <code>SingleNamedIndexManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public SingleNamedIndexManager()
        throws TorqueException
    {
        super();
    }

}
