package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages SingleUnnamedUnique objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to SingleUnnamedUniqueBean
 */
 
public class SingleUnnamedUniqueManager
    extends org.apache.torque.test.manager.base.BaseSingleUnnamedUniqueManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841783L;


    /**
     * Creates a new <code>SingleUnnamedUniqueManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public SingleUnnamedUniqueManager()
        throws TorqueException
    {
        super();
    }

}
