package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages SingleNamedUnique objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to SingleNamedUniqueBean
 */
 
public class SingleNamedUniqueManager
    extends org.apache.torque.test.manager.base.BaseSingleNamedUniqueManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841780L;


    /**
     * Creates a new <code>SingleNamedUniqueManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public SingleNamedUniqueManager()
        throws TorqueException
    {
        super();
    }

}
