package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages SkipSql objects.
 *
 * table without SQL
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to SkipSqlBean
 */
 
public class SkipSqlManager
    extends org.apache.torque.test.manager.base.BaseSkipSqlManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841849L;


    /**
     * Creates a new <code>SkipSqlManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public SkipSqlManager()
        throws TorqueException
    {
        super();
    }

}
