package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages Summarize1 objects.
 *
 * Test table for summaryHelper test
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to Summarize1Bean
 */
 
public class Summarize1Manager
    extends org.apache.torque.test.manager.base.BaseSummarize1Manager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841846L;


    /**
     * Creates a new <code>Summarize1Manager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public Summarize1Manager()
        throws TorqueException
    {
        super();
    }

}
