package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages IfcTable objects.
 *
 * this table implements an interface
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to IfcTableBean
 */
 
public class TestInterfaceManager
    extends org.apache.torque.test.manager.base.BaseTestInterfaceManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841854L;


    /**
     * Creates a new <code>TestInterfaceManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public TestInterfaceManager()
        throws TorqueException
    {
        super();
    }

}
