package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages TimestampPk objects.
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to TimestampPkBean
 */
 
public class TimestampPkManager
    extends org.apache.torque.test.manager.base.BaseTimestampPkManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841794L;


    /**
     * Creates a new <code>TimestampPkManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public TimestampPkManager()
        throws TorqueException
    {
        super();
    }

}
