package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages TypesObject objects.
 *
 * used to test the handling for all supported types
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to TypesObjectBean
 */
 
public class TypesObjectManager
    extends org.apache.torque.test.manager.base.BaseTypesObjectManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841874L;


    /**
     * Creates a new <code>TypesObjectManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public TypesObjectManager()
        throws TorqueException
    {
        super();
    }

}
