package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages VarbinaryType objects.
 *
 * Table to test VARBINARY type
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to VarbinaryTypeBean
 */
 
public class VarbinaryTypeManager
    extends org.apache.torque.test.manager.base.BaseVarbinaryTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841888L;


    /**
     * Creates a new <code>VarbinaryTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public VarbinaryTypeManager()
        throws TorqueException
    {
        super();
    }

}
