package org.apache.torque.test.manager;

import org.apache.torque.TorqueException;

/**
 * This class manages VarcharType objects.
 *
 * Table to test VARCHAR type
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to VarcharTypeBean
 */
 
public class VarcharTypeManager
    extends org.apache.torque.test.manager.base.BaseVarcharTypeManager
{
    /** Serial version */
    private static final long serialVersionUID = 1643301841903L;


    /**
     * Creates a new <code>VarcharTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public VarcharTypeManager()
        throws TorqueException
    {
        super();
    }

}
