package org.apache.torque.test.bean;

import java.io.Serializable;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:01 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class InheritanceChildCBean
    extends InheritanceTestBean
    implements Serializable
{
}
