package org.apache.torque.test.bean;

/**
 * Table to test multiple references to different tables
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:00 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class MultiRefBean
    extends org.apache.torque.test.bean.BaseMultiRefBean
{
    /** Serial version */
    private static final long serialVersionUID = 1643301840028L;



}
