package org.apache.torque.test.bean;

/**
 * table with a non-nullable integer primitive foreign key           which references a non-primary-key column in the foreign table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:00 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class NonPkPIntegerFkBean
    extends org.apache.torque.test.bean.BaseNonPkPIntegerFkBean
{
    /** Serial version */
    private static final long serialVersionUID = 1643301840001L;



}
