package org.apache.torque.test.bean;

/**
 * Table used for database map initialisation checks
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class NotUsedBeforeMapInitBean
    extends org.apache.torque.test.bean.BaseNotUsedBeforeMapInitBean
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839961L;



}
