package org.apache.torque.test.bean;

/**
 * this table implements optimistic Locking with the selectForUpdate mode
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:44:00 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class OptimisticLockingBean
    extends org.apache.torque.test.bean.BaseOptimisticLockingBean
{
    /** Serial version */
    private static final long serialVersionUID = 1643301840131L;



}
