package org.apache.torque.test.recordmapper;

import org.apache.torque.test.recordmapper.base.BaseCurrentTimeTableRecordMapper;

/**
 * Maps ResultSet rows into CurrentTimeTable objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class CurrentTimeTableRecordMapper extends BaseCurrentTimeTableRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839179L;



}
