package org.apache.torque.test.recordmapper;

import org.apache.torque.test.recordmapper.base.BaseIfcTableRecordMapper;

/**
 * Maps ResultSet rows into IfcTable objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class IfcTableRecordMapper extends BaseIfcTableRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839333L;



}
