package org.apache.torque.test.recordmapper;

import org.apache.torque.test.recordmapper.base.BaseLongvarbinaryTypeRecordMapper;

/**
 * Maps ResultSet rows into LongvarbinaryType objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class LongvarbinaryTypeRecordMapper extends BaseLongvarbinaryTypeRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839363L;



}
