package org.apache.torque.test.recordmapper;

import org.apache.torque.test.recordmapper.base.BaseOptionTableRecordMapper;

/**
 * Maps ResultSet rows into OptionTable objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class OptionTableRecordMapper extends BaseOptionTableRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839167L;



}
