package org.apache.torque.test.recordmapper;

import org.apache.torque.test.recordmapper.base.BaseReferenceToExtSchemaRecordMapper;

/**
 * Maps ResultSet rows into ReferenceToExtSchema objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class ReferenceToExtSchemaRecordMapper extends BaseReferenceToExtSchemaRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839310L;



}
