package org.apache.torque.test.recordmapper;

import org.apache.torque.test.recordmapper.base.BaseSaveMethodInPeerRecordMapper;

/**
 * Maps ResultSet rows into SaveMethodInPeer objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class SaveMethodInPeerRecordMapper extends BaseSaveMethodInPeerRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839281L;



}
