package org.apache.torque.test.recordmapper;

import org.apache.torque.test.recordmapper.base.BaseSkipSqlRecordMapper;

/**
 * Maps ResultSet rows into SkipSql objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class SkipSqlRecordMapper extends BaseSkipSqlRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839329L;



}
