package org.apache.torque.test.recordmapper;

import org.apache.torque.test.recordmapper.base.BaseSummarize1RecordMapper;

/**
 * Maps ResultSet rows into Summarize1 objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class Summarize1RecordMapper extends BaseSummarize1RecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839327L;



}
