package org.apache.torque.test.recordmapper;

import org.apache.torque.test.recordmapper.base.BaseVarcharTypeRecordMapper;

/**
 * Maps ResultSet rows into VarcharType objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:59 CET 2022]
 *
 */
public class VarcharTypeRecordMapper extends BaseVarcharTypeRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1643301839373L;



}
