package org.apache.torque.test.dbobject;


/**
 * this table is used for testing enum values in columns
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:50 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class EnumTable
    extends org.apache.torque.test.dbobject.base.BaseEnumTable
{
    /** Serial version */
    private static final long serialVersionUID = 1643301830970L;



}
