package org.apache.torque.test.dbobject;


/**
 * Table to test inheritance with classnames stored in the inheritance column
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:50 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class InheritanceClassnameTest
    extends org.apache.torque.test.dbobject.base.BaseInheritanceClassnameTest
{
    /** Serial version */
    private static final long serialVersionUID = 1643301830948L;



}
