package org.apache.torque.test.dbobject;


/**
 * table with a primitive integer foreign key           which references a primary key column in the foreign table           and has a default value
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:50 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class PIntegerFkWithDefault
    extends org.apache.torque.test.dbobject.base.BasePIntegerFkWithDefault
{
    /** Serial version */
    private static final long serialVersionUID = 1643301830790L;



}
