package org.apache.torque.test.dbobject;


/**
 * Table to test VARCHAR type
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:51 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class VarcharType
    extends org.apache.torque.test.dbobject.base.BaseVarcharType
{
    /** Serial version */
    private static final long serialVersionUID = 1643301831012L;



}
