package org.apache.torque.test.peer;

/**
 * Author table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:54 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class AuthorPeerImpl
    extends org.apache.torque.test.peer.base.BaseAuthorPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1643301834959L;



}
