package org.apache.torque.test.peer;

/**
 * table with a composite foreign key consisting of an integer           and a varchar column, not pointing to the primary key            of the referenced table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:54 CET 2022]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class CompNonpkFkPeer
    extends org.apache.torque.test.peer.base.BaseCompNonpkFkPeer
{

}
