package org.apache.torque.test.peer;

/**
 * table with a composite primary key a part of which           is a foreign key column which references the non-composite            primary key of another table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:55 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class CompPkContainsFkPeerImpl
    extends org.apache.torque.test.peer.base.BaseCompPkContainsFkPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1643301835040L;



}
