package org.apache.torque.test.peer;

/**
 * table with a composite foreign key consisting of an integer           and a varchar column, not pointing to the primary key            of the referenced table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:55 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class CompNonpkFkPeerImpl
    extends org.apache.torque.test.peer.base.BaseCompNonpkFkPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1643301835048L;



}
