package org.apache.torque.test.peer;

/**
 * table with a composite primary key a part of which           is a foreign key column which references the non-composite            primary key of another table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:54 CET 2022]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class CompPkContainsFkPeer
    extends org.apache.torque.test.peer.base.BaseCompPkContainsFkPeer
{

}
