
package org.apache.torque.test.peer;

/**
 * this table implements a local interface
 *
 * This is an interface that should be filled with the public api of the
 * LocalIfcTablePeerImpl objects.
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:54 CET 2022]
 *  * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public interface LocalTestPeerInterface
{
}
