package org.apache.torque.test.peer;

/**
 * Table to test LONGVARBINARY type
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:55 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class LongvarbinaryTypePeerImpl
    extends org.apache.torque.test.peer.base.BaseLongvarbinaryTypePeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1643301835190L;



}
