package org.apache.torque.test.peer;

/**
 * table with a non-nullable integer primitive foreign key           which references a non-primary-key column in the foreign table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:55 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class NonPkPIntegerFkPeerImpl
    extends org.apache.torque.test.peer.base.BaseNonPkPIntegerFkPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1643301835008L;



}
