package org.apache.torque.test.peer;

/**
 * this table implements optimistic Locking with the simple select mode
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 27 17:43:55 CET 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class OptimisticLockingSimplePeerImpl
    extends org.apache.torque.test.peer.base.BaseOptimisticLockingSimplePeerImpl
    implements org.apache.torque.OptimisticLockingPeerInterface<org.apache.torque.test.dbobject.OptimisticLockingSimple>
{
    /** Serial version */
    private static final long serialVersionUID = 1643301835158L;



}
